// MODEL: project portfolio data. Each project's screenshots live in /projects/<slug>/
// and are referenced by relative path, so this file is the single source of truth
// for what appears in the Projects section (rendered by js/views/projects-view.js).

const projectsData = [
  {
    slug: 'ualcprpva',
    index: '01',
    category: 'academic',
    title: 'UALC Pre-Registration System',
    period: 'Mar 2026 - May 2026',
    description: 'A full-stack pre-registration system built for the University of Antique, Libertad Campus, with role-based access control and Google OAuth login. Includes real-time dashboards, PWA support, and secure file uploads with email OTP verification.',
    stack: ['Laravel 12', 'PHP 8.2', 'MySQL', 'Bootstrap', 'Tailwind CSS', 'Chart.js'],
    images: [
      { file: 'ualcprpva-login.png', label: 'Login' },
      { file: 'ualcprpva-register.png', label: 'Register' },
      { file: 'ualcprpva-studentdashboard.png', label: 'Student dashboard' },
      { file: 'ualcprpva-admindashboard.png', label: 'Admin dashboard' },
      { file: 'ualcprpva-superadmindashboard.png', label: 'Super admin dashboard' },
    ],
  },
  {
    slug: 'touristrack',
    index: '02',
    category: 'travel & tourism',
    title: 'Tourist Track System',
    period: 'Feb 2026 - Apr 2026',
    description: 'A QR-code-based visitor check-in system with live dashboard statistics and automated PDF/CSV reporting. Integrated with Google OAuth login, OTP email verification, and reCAPTCHA v2 bot protection.',
    stack: ['Laravel 12', 'MySQL', 'Pusher', 'DomPDF', 'Bootstrap'],
    images: [
      { file: 'homepage1.png', label: 'Homepage' },
      { file: 'homepage2.png', label: 'Homepage' },
      { file: 'homepage3.png', label: 'Homepage' },
      { file: 'homepage4.png', label: 'Homepage' },
      { file: 'homepage5.png', label: 'Homepage' },
      { file: 'homepage6.png', label: 'Homepage' },
      { file: 'homepage7.png', label: 'Homepage' },
      { file: 'homepage8.png', label: 'Homepage' },
      { file: 'loginpage.png', label: 'Login' },
      { file: 'tourist-register.png', label: 'Tourist register' },
      { file: 'staffdashboard.png', label: 'Staff dashboard' },
      { file: 'superadmin-dashboard.png', label: 'Super admin dashboard' },
    ],
  },
  {
    slug: 'hydrohubconnect',
    index: '03',
    category: 'business ops',
    title: 'Hydro Hub Water Refilling Station',
    period: 'Oct 2025 - Dec 2025',
    description: 'A multi-role delivery management platform with real-time GPS tracking and PayMongo payment integration. Includes branch, inventory, and container management modules with PDF/Word report generation.',
    stack: ['PHP', 'MySQL', 'Bootstrap', 'Leaflet.js', 'PayMongo API'],
    images: [
      { file: 'home-page0.png', label: 'Homepage' },
      { file: 'home-page1.png', label: 'Homepage' },
      { file: 'home-page2.png', label: 'Homepage' },
      { file: 'home-page3.png', label: 'Homepage' },
      { file: 'home-page4.png', label: 'Homepage' },
      { file: 'home-page5.png', label: 'Homepage' },
      { file: 'home-page6.png', label: 'Homepage' },
      { file: 'login-page.png', label: 'Login' },
      { file: 'register-page.png', label: 'Register' },
      { file: 'user-dashboard.png', label: 'User dashboard' },
      { file: 'driver-dashboard.png', label: 'Driver dashboard' },
      { file: 'staff-dashboard.png', label: 'Staff dashboard' },
      { file: 'admin-dashboard.png', label: 'Admin dashboard' },
    ],
  },
  {
    slug: 'pagdumarahostel',
    index: '04',
    category: 'hospitality',
    title: 'Pagdumara Hostel Management System',
    period: 'Oct 2025 - Dec 2025',
    description: 'A hostel operations system covering bookings, staff scheduling, attendance, and task management. Includes role-based dashboards, activity logging, and an automated database backup utility.',
    stack: ['PHP', 'MariaDB', 'JavaScript', 'Chart.js'],
    images: [
      { file: 'ualchostel-login.png', label: 'Login' },
      { file: 'ualchostel-register.png', label: 'Register' },
      { file: 'ualchostel-staff-dashboard.png', label: 'Staff dashboard' },
      { file: 'ualchostel-admin-dashboard.png', label: 'Admin dashboard' },
    ],
  },
];
