// MODEL: project portfolio data. Each project's screenshots live in /projects/<slug>/
// and are referenced by relative path, so this file is the single source of truth
// for what appears in the Projects section (rendered by js/views/projects-view.js).

const projectsData = [
  {
    slug: 'ualcprpva',
    index: '01',
    category: 'academic',
    title: 'UALC Pre-Registration System',
    period: 'Mar 2026 - May 2026',
    liveUrl: 'https://ualc-prereg.site/',
    description: 'A full-stack pre-registration system built for the University of Antique, Libertad Campus, with role-based access control and Google OAuth login. Includes real-time dashboards, PWA support, and secure file uploads with email OTP verification.',
    stack: ['Laravel 12', 'PHP 8.2', 'MySQL', 'Bootstrap', 'Tailwind CSS', 'Chart.js'],
    images: [
      { file: 'superadmin-dashboard.png', label: 'Super admin dashboard' },
      { file: 'login.png', label: 'Login' },
      { file: 'register.png', label: 'Register' },
      { file: 'students.png', label: 'Student management' },
    ],
  },
  {
    slug: 'touristrack',
    index: '02',
    category: 'travel & tourism',
    title: 'Tourist Track System',
    period: 'Feb 2026 - Apr 2026',
    liveUrl: 'https://touristtrack.site/',
    description: 'A QR-code-based visitor check-in system with live dashboard statistics and automated PDF/CSV reporting. Integrated with Google OAuth login, OTP email verification, and reCAPTCHA v2 bot protection.',
    stack: ['Laravel 12', 'MySQL', 'Pusher', 'DomPDF', 'Bootstrap'],
    images: [
      { file: 'homepage.png', label: 'Homepage' },
      { file: 'attractions.png', label: 'Attractions index' },
      { file: 'login.png', label: 'Login' },
      { file: 'register.png', label: 'Tourist register' },
      { file: 'admin-dashboard.png', label: 'Super admin dashboard' },
      { file: 'tourists.png', label: 'Tourists list' },
    ],
  },
  {
    slug: 'cafehugo',
    index: '03',
    category: 'café operations',
    title: 'Café Hugo Operations System',
    period: 'Sep 2026 - Present',
    liveUrl: 'https://cafehugo.online/',
    description: 'Contributed to a team-built three-portal café platform (customer, staff, admin) covering online ordering, a walk-in POS terminal, reservations, inventory with low-stock alerts, manual GCash payment-proof verification, and SMS updates. Includes Pest feature tests.',
    stack: ['Laravel 13', 'PHP 8.3', 'MySQL', 'Pest'],
    images: [
      { file: 'pos-terminal.png', label: 'POS terminal' },
      { file: 'homepage.png', label: 'Homepage' },
      { file: 'menu.png', label: 'Public menu' },
      { file: 'admin-dashboard.png', label: 'Admin dashboard' },
    ],
  },
  {
    slug: 'smartidmaker',
    index: '04',
    category: 'desktop software',
    title: 'Smart ID Maker',
    period: 'Jul 2026 - Present',
    description: 'An offline ID card application for schools, training centers, and review centers: multi-institution student management, Excel and photo imports, a drag-and-drop template designer, QR codes, and batch PDF/PVC printing. Ships as a Windows desktop app.',
    stack: ['Laravel 13', 'PHP 8.3', 'SQLite', 'Alpine.js', 'Electron'],
    images: [
      { file: 'app-login.png', label: 'Desktop app sign-in' },
    ],
  },
  {
    slug: 'hydrohubconnect',
    index: '05',
    category: 'business ops',
    title: 'Hydro Hub Water Refilling Station',
    period: 'Oct 2025 - Dec 2025',
    description: 'A multi-role delivery management platform with real-time GPS tracking and PayMongo payment integration. Includes branch, inventory, and container management modules with PDF/Word report generation.',
    stack: ['PHP', 'MySQL', 'Bootstrap', 'Leaflet.js', 'PayMongo API'],
    images: [
      { file: 'home-page0.png', label: 'Homepage' },
      { file: 'home-page1.png', label: 'Homepage' },
      { file: 'home-page2.png', label: 'Homepage' },
      { file: 'home-page3.png', label: 'Homepage' },
      { file: 'home-page4.png', label: 'Homepage' },
      { file: 'home-page5.png', label: 'Homepage' },
      { file: 'home-page6.png', label: 'Homepage' },
      { file: 'login-page.png', label: 'Login' },
      { file: 'register-page.png', label: 'Register' },
      { file: 'user-dashboard.png', label: 'User dashboard' },
      { file: 'driver-dashboard.png', label: 'Driver dashboard' },
      { file: 'staff-dashboard.png', label: 'Staff dashboard' },
      { file: 'admin-dashboard.png', label: 'Admin dashboard' },
    ],
  },
  {
    slug: 'pagdumarahostel',
    index: '06',
    category: 'hospitality',
    title: 'Pagdumara Hostel Management System',
    period: 'Oct 2025 - Dec 2025',
    description: 'A hostel operations system covering bookings, staff scheduling, attendance, and task management. Includes role-based dashboards, activity logging, and an automated database backup utility.',
    stack: ['PHP', 'MariaDB', 'JavaScript', 'Chart.js'],
    images: [
      { file: 'ualchostel-login.png', label: 'Login' },
      { file: 'ualchostel-register.png', label: 'Register' },
      { file: 'ualchostel-staff-dashboard.png', label: 'Staff dashboard' },
      { file: 'ualchostel-admin-dashboard.png', label: 'Admin dashboard' },
    ],
  },
];
